2015-October-06@11:56:52,989 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.NullPointerException
	at com.copel.dao.BancoDeDados.fechar(BancoDeDados.java:116)
	at com.copel.dao.Proxy.carregar(Proxy.java:62)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@11:58:11,140 - Erro ao carregar conta
Início da mensagem de erro:
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getInt(RS.java:293)
	at com.copel.sgd.dao.ContaDAO.lerColunas(ContaDAO.java:58)
	at com.copel.dao.BancoDeDados.carregar(BancoDeDados.java:206)
	at com.copel.dao.Proxy.carregar(Proxy.java:59)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@11:58:11,140 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.Exception: Erro ao carregar conta
	at com.copel.Log.adicionarEJogarExcecao(Log.java:91)
	at com.copel.dao.Proxy.carregar(Proxy.java:63)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:00:41,297 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.NullPointerException
	at com.copel.dao.BancoDeDados.fechar(BancoDeDados.java:116)
	at com.copel.dao.Proxy.carregar(Proxy.java:62)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:01:41,841 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.NullPointerException
	at com.copel.dao.BancoDeDados.fechar(BancoDeDados.java:116)
	at com.copel.dao.Proxy.carregar(Proxy.java:62)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:04:19,808 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.NullPointerException
	at com.copel.dao.BancoDeDados.fechar(BancoDeDados.java:116)
	at com.copel.dao.Proxy.carregar(Proxy.java:62)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:09:31,097 - Erro ao carregar conta
Início da mensagem de erro:
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getInt(RS.java:293)
	at com.copel.sgd.dao.ContaDAO.lerColunas(ContaDAO.java:58)
	at com.copel.dao.BancoDeDados.carregar(BancoDeDados.java:206)
	at com.copel.dao.Proxy.carregar(Proxy.java:59)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:09:31,425 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.Exception: Erro ao carregar conta
	at com.copel.Log.adicionarEJogarExcecao(Log.java:91)
	at com.copel.dao.Proxy.carregar(Proxy.java:63)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:10:27,430 - Erro ao carregar conta
Início da mensagem de erro:
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getInt(RS.java:293)
	at com.copel.sgd.dao.ContaDAO.lerColunas(ContaDAO.java:58)
	at com.copel.dao.BancoDeDados.carregar(BancoDeDados.java:206)
	at com.copel.dao.Proxy.carregar(Proxy.java:59)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:10:27,461 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.Exception: Erro ao carregar conta
	at com.copel.Log.adicionarEJogarExcecao(Log.java:91)
	at com.copel.dao.Proxy.carregar(Proxy.java:63)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:12:50,621 - Erro ao carregar conta
Início da mensagem de erro:
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getInt(RS.java:293)
	at com.copel.sgd.dao.ContaDAO.lerColunas(ContaDAO.java:58)
	at com.copel.dao.BancoDeDados.carregar(BancoDeDados.java:206)
	at com.copel.dao.Proxy.carregar(Proxy.java:59)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:12:50,683 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.Exception: Erro ao carregar conta
	at com.copel.Log.adicionarEJogarExcecao(Log.java:91)
	at com.copel.dao.Proxy.carregar(Proxy.java:63)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:13:49,216 - Erro ao carregar conta
Início da mensagem de erro:
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getInt(RS.java:293)
	at com.copel.sgd.dao.ContaDAO.lerColunas(ContaDAO.java:58)
	at com.copel.dao.BancoDeDados.carregar(BancoDeDados.java:206)
	at com.copel.dao.Proxy.carregar(Proxy.java:59)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:13:49,231 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.Exception: Erro ao carregar conta
	at com.copel.Log.adicionarEJogarExcecao(Log.java:91)
	at com.copel.dao.Proxy.carregar(Proxy.java:63)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:21:57,133 - Erro ao carregar conta
Início da mensagem de erro:
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getInt(RS.java:293)
	at com.copel.sgd.dao.ContaDAO.lerColunas(ContaDAO.java:58)
	at com.copel.dao.BancoDeDados.carregar(BancoDeDados.java:206)
	at com.copel.dao.Proxy.carregar(Proxy.java:59)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
2015-October-06@12:21:57,164 - Erro ao carregar usuário C050883 para efetuar logon. Consulte o administrador.
Início da mensagem de erro:
java.lang.Exception: Erro ao carregar conta
	at com.copel.Log.adicionarEJogarExcecao(Log.java:91)
	at com.copel.dao.Proxy.carregar(Proxy.java:63)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:31)
	at com.copel.sgd.fachada.SGD.carregarUsuario(SGD.java:123)
	at com.copel.sgd.fachada.SGD$1.run(SGD.java:43)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
